# Generated by Django 4.2.4 on 2023-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dedicated_adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avaible', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
