# Generated by Django 4.2.4 on 2023-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicated_adress',
            name='date_sibnet_adress',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dedicated_adress',
            name='network_adress',
            field=models.CharField(default=76564534, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dedicated_adress',
            name='sibnet_address',
            field=models.CharField(default=324565768, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='network_adress',
            field=models.CharField(default=123423546, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='uuid',
            field=models.CharField(default=4323564758957654, max_length=32),
            preserve_default=False,
        ),
    ]
