# Generated by Django 4.2.4 on 2023-09-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0002_dedicated_adress_date_sibnet_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='uuid',
        ),
    ]
