# Generated by Django 4.2.4 on 2023-09-01 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0003_remove_network_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
