# Generated by Django 4.2.4 on 2023-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0004_network_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicated_adress',
            name='network_uuid',
            field=models.CharField(default=242354678676544, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dedicated_adress',
            name='avaible',
            field=models.CharField(default='YES', max_length=5),
        ),
    ]
