# Generated by Django 4.2.4 on 2023-09-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0005_dedicated_adress_network_uuid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dedicated_adress',
            new_name='dedicated_address',
        ),
        migrations.RenameField(
            model_name='dedicated_address',
            old_name='date_sibnet_adress',
            new_name='date_sibnet_address',
        ),
        migrations.RenameField(
            model_name='dedicated_address',
            old_name='network_adress',
            new_name='network_address',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network_adress',
            new_name='network_address',
        ),
    ]
