# Generated by Django 4.2.4 on 2023-09-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0006_rename_dedicated_adress_dedicated_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dedicated_address',
            new_name='DedicatedAddreses',
        ),
    ]
