# Generated by Django 4.2.4 on 2023-09-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0007_rename_dedicated_address_dedicatedaddreses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dedicatedaddreses',
            old_name='sibnet_address',
            new_name='dedicated_address',
        ),
    ]
