# Generated by Django 4.2.4 on 2023-09-13 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0008_rename_sibnet_address_dedicatedaddreses_dedicated_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='network_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
