# Generated by Django 4.2.4 on 2023-09-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0009_alter_dedicatedaddreses_network_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dedicatedaddreses',
            old_name='network_uuid',
            new_name='dedicated_address_uuid',
        ),
    ]
