# Generated by Django 4.2.4 on 2023-09-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0010_rename_network_uuid_dedicatedaddreses_dedicated_address_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dedicatedaddreses',
            old_name='date_sibnet_address',
            new_name='address_date',
        ),
        migrations.RenameField(
            model_name='dedicatedaddreses',
            old_name='dedicated_address_uuid',
            new_name='uuid',
        ),
    ]
