# Generated by Django 4.2.4 on 2023-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0011_rename_date_sibnet_address_dedicatedaddreses_address_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='address_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
