# Generated by Django 4.2.4 on 2023-09-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0012_alter_dedicatedaddreses_address_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dedicatedaddreses',
            old_name='uuid',
            new_name='dedicated_uuid',
        ),
    ]
