# Generated by Django 4.2.4 on 2023-09-13 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0013_rename_uuid_dedicatedaddreses_dedicated_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='address_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='dedicated_address',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='dedicated_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='dedicatedaddreses',
            name='network_address',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_address',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
